### ISSUE TITLE
Sleep phase weird metric behavior

### ISSUE THREAD

**Issue by ZachariahPang** [prob-ml/bliss#164]
## Metric values behave weirdly but loss seems to be normal on m2
<img width="1400" alt="Screen Shot 2021-01-03 at 18 53 44" src="https://user-images.githubusercontent.com/46454028/103496989-0324c600-4df5-11eb-8a8b-0cab75da597f.png">

The metric `val_acc_counts`(shown as star_count_acc) is almost always 0.
The metric `val_gal_counts`(shown as galaxy_counts_acc) is the constant 0.
The metric `val_locs_median_mse`(shown as locs_median_mse) is almost always 0.5.
The metric `val_fluxes_avg_err`(shown as fluxes_avg_err) is almost inf.

**To reproduce**
```shell
git checkout a58ffde
cd bin
python tuning.py model=m2 dataset=m2 training=m2 optimizer=m2
```
General logs are printed in the terminal, detailed logs are available in Tensorboard
```shell
tensorboard --logdir=outputs/hyperparameter_tuning
```
## Metric behave normally with default 

<img width="1405" alt="Screen Shot 2021-01-03 at 4 58 46 PM" src="https://user-images.githubusercontent.com/46454028/103497434-5f3c1a00-4df6-11eb-9e27-a8c07c1223bf.png">
This image is from @zzhaozhe-profolio.
 
**To reproduce**
```shell
git checkout a58ffde
cd bin
python tuning.py tuning=m2
```
```shell
tensorboard --logdir=outputs/hyperparameter_tuning
```

This issue seems to be more related to modeling itself rather than the raytune.
Any suggestions?

**Comment by zzhaozhe-profolio** [comment]
Is this because the source counts for each batch dose not always match (see the code [here](https://github.com/prob-ml/bliss/blob/master/bliss/sleep.py#L377) and below)? Seems that if the counts does not match, `locs_mse_vec` and `fluxes_mse_vec` won't be appended. Two metrics: `locs_median_mse` and `fluxes_avg_err` will always be default.

I checked if `true_n_sources_i ` matched with `true_n_sources_i`, and they failed the condition every time. @ismael-mendoza @Runjing-Liu120 Is this expected? 

```
        locs_mse_vec = []
        fluxes_mse_vec = []
        for i in range(batch_size):
            true_n_sources_i = true_params["n_sources"][i]
            n_sources_i = estimates["n_sources"][i]

            # only compare locations for mse if counts match.
            if true_n_sources_i == n_sources_i:

                # prepare locs and get them in units of pixels.
                true_locs_i = true_locs[i].view(-1, 2)
                true_locs_i = true_locs_i[: int(true_n_sources_i)] * slen
                locs_i = est_locs[i].view(-1, 2)[: int(n_sources_i)] * slen
```

**Comment by ismael-mendoza** [comment]
Hi all, thanks for opening this issue. This is partially related to the issue #137 where I realized that the current metrics can be misleading particularly in situations like the m2 test where there are so many stars that it's basically impossible to get the correct number of counts (which is why you get this behavior @ZachariahPang as @zzhaozhe-profolio  pointed out). 

A much better approach is to match each predicted star with each true star based on the distance between them and then use this to report metrics we care about. Let's try to implement this in the new PR #167 , I'll try give some pointers soon @zzhaozhe-profolio
