### ISSUE TITLE
remove fitsio dependency

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#190]
I noticed that astropy has its own version of FITS `astropy.io.fits`, would it be possible to use this and avoid having `fitsio` as a dependency? We only use `fitsio` in `sdss.py` in one function so it would be nice if we could rewrite this using astropy (although I'm not sure exactly how to translate this to astropy code) 

```
def read_psf(psf_fit_file, band=2):
    psfield = fitsio.FITS(psf_fit_file)
    hdu = psfield[band + 1]
    psf = hdu.read()
    return {"hdu": hdu, "psf": psf}
```

**Comment by dereklhansen** [comment]
Some relevant links:
- https://astro-docs.readthedocs.io/en/latest/io/fits/
- Comparison between fitsio and astropy.io.fits: https://docs.astropy.org/en/stable/io/fits/appendix/faq.html#comparison-with-other-fits-readers

**Comment by dereklhansen** [comment]
I can look into seeing if astropy can be a drop-in replacement here.

 Based on the second link, it seems that fitsio is faster on small images (because it processes header files faster), but astropy.io.fits is faster on larger images because it uses a more standard memory-map interface. My guess is that scaleability is more important than reading small images a bit quicker.

**Comment by jeff-regier** [comment]
It’d be nice to have fewer dependencies, ie just astropy. Unfortunately astropy.io.fits isn’t a drop-in replacement for fitsio

**Comment by ismael-mendoza** [comment]
> It’d be nice to have fewer dependencies, ie just astropy. Unfortunately astropy.io.fits isn’t a drop-in replacement for fitsio

ah ok, I thought it could be. Could you explain why? If you are sure though, feel free to close this issue. Thanks!

**Comment by jeff-regier** [comment]
It might be worth converting it anyway. I’ve looked into it before and there some differences in syntax
