### ISSUE TITLE
test tune fails on the GPU

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#257]
I'm about to merge #252 , but I just tested this on master before merging and when running e.g. 

```
pytest tests/test_tune.py --gpus 3
```

I get a very long error which ends up in: 

```
FAILED tests/test_tune.py::TestTune::test_tune_run - ray.tune.error.TuneError: ('Trials did not complete', [sleep_trainable_22ecd146, sleep_trainable_22ecd147])
```
Is this a known issue or expected?

**Comment by ZachariahPang** [comment]
`tets_tune` by default run on two gpus if multiple gpus are available. It's currently not aware of the pytest `--gpus` argument and always uses the first two gpus in the system. The gpu 0 on our server has been occupied with 2270mb memory for a while and I believe the error is an out-of-memory error. If that 2270mb is expected to be free later on then I think it's not a problem. But I'm not sure because it's been occupied for quite a while and I think it might an opened jupyter notebook or something like that.

**Comment by jeff-regier** [comment]
@ZachariahPang Would you change `test_tune.py` so that it is aware of the `--gpus` flag?  (even if that means pytest coverage will be lower)

**Comment by ZachariahPang** [comment]
> @ZachariahPang Would you change `test_tune.py` so that it is aware of the `--gpus` flag? (even if that means pytest coverage will be lower)

I would need some time to think about the best approach. I couldn't find an easy way to select specific gpus for `ray` other than using `CUDA_VISIBLE_DEVICES`. However, this would cause trouble since the `--gpus=3` flag would then try to choose a non-existing gpu exposed to the session and throw an error. And  `--gpus` is a global option for the entire tests so I want to be careful before trying to change this.

An easier approach, if acceptable, is to let `test_tune` to only search for smaller architectures so that it won't easily throw an error because of slightly occupied gpus.

**Comment by jeff-regier** [comment]
I see, maybe then we shouldn't be using a `--gpus` flag at all. Instead if we want to run the unit tests on GPU 3, for example, we  could run
```
CUDA_VISIBLE_DEVICES=3 pytest
```

**Comment by ZachariahPang** [comment]
> I see, maybe then we shouldn't be using a `--gpus` flag at all. Instead if we want to run the unit tests on GPU 3, for example, we could run
> 
> ```
> CUDA_VISIBLE_DEVICES=3 pytest
> ```

I agree. At least for handling `ray`, this would seem to be the more robust approach. Do you want me to fix `test_tune` as in
> An easier approach, if acceptable, is to let test_tune to only search for smaller architectures so that it won't easily throw an error because of slightly occupied gpus.

or should we discuss this during our meeting before making changes?

**Comment by jeff-regier** [comment]
Let's discuss it first
