### ISSUE TITLE
load_state_dict instead of load_from_checkpoint?

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#328]
During our meeting Wednesday, it came up that some of the models which are trained earlier, such as the galaxy autoencoder, are imported using load_from_checkpoint(). load_from_checkpoint() comes from Pytorch lightning and is a class method. For example,

https://github.com/prob-ml/bliss/blob/287117944fe8e9fcdeae5b895b44c86e972c5251/bliss/models/decoder.py#L751-L767

One problem with this is that it forces the "GalaxyTileDecoder" to have as an argument the "autoencoder_ckpt" variable, when ideally it should be passed the autoencoder object as-is (without having to know how to initialize it).

```python 
class GalaxyTileDecoder(nn.Module): 
     def __init__( 
         self, 
         n_bands, 
         tile_slen, 
         ptile_slen, 
         gal_slen, 
         n_galaxy_params, 
         autoencoder :  galaxy_net.OneCenteredGalaxyAE
     ): 
         super().__init__() 
         self.n_bands = n_bands 
         self.tiler = Tiler(tile_slen, ptile_slen) 
         self.ptile_slen = ptile_slen 
```

The nice thing about this setup is that we could use Hydra's new recursive config (#315) to initialize the autoencoder by calling its constructor ("__init__()") with the given keyword arguments. However, the problem is that "load_from_checkpoint()" is a class method, making it not amenable to calling from an object's constructor.

Instead, I think we can just use the state_dict part of the checkpoint, since the autoencoder is being integrated as a piece of a larger model which has an entirely separate training procedure.

For example, we can do this

```python 
class OneCenteredGalaxyAE(LightningModule)
     def __init__( 
         self, 
... # Constructor arguments
checkpoint_file=None,
     ): 
         super().__init__() 
         ... # Call constructor
         if checkpoint_file is not None:
                self.load_state_dict(torch.load(checkpoint_file)["state_dict"])
```

Then the object can be initialized with Hydra

**Comment by dereklhansen** [comment]
I'm going to wait until #315 before moving on this, but I think it'll make things simpler and better decouple the autoencoder from the rest of the model

**Comment by ZachariahPang** [comment]
Does this mean that we have to make sure the constructor arguments for `OneCenteredGalaxyAE` are in sync with the `state_dict`? Otherwise we might run into unexpected behavior when the ckpt weights was trained on a different setup than the constructor arguments we passed in. We then rely on loading state_dict error to catch that but it might not always throw an error.

This is related to one issue currently on #315.  Here`SleepPhase` takes in the already initialized `encoder` and `decoder` objects. Then we can't really save those two objects with `self.save_hyperparameters`. It's fine at this stage.  
https://github.com/prob-ml/bliss/blob/e550fc44563cb86cf5e67103ff27f3733f598bb6/bliss/sleep.py#L135-L157

However, it becomes problematic during the predicting phase. We now rely on using the correct `cfg` to initialize `encoder` and `decoder` and then load their weights. This means that our `SleepPhase`'s setup is separated into two pieces. To correctly load the setup, we need those two pieces to be always in sync. However, the setup on master branch loads evertying in ckpt which has both the constructor recipe and the weight and it's never out of sync so we don't worry the model we loaded in might have some surprising behavior.  I think this is especially beneficial in predicting phase as we always want to restore a model with everything needed to do that, preferably in one place.  
https://github.com/prob-ml/bliss/blob/e550fc44563cb86cf5e67103ff27f3733f598bb6/bliss/predict.py#L74-L83
