### ISSUE TITLE
Sample background rather than using a fixed value when training

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#466]
@jeff-regier  mentioned that this might be a good thing to do down the line and might make the algorithm more robust. Not sure if redundant with or related to #464

**Comment by dereklhansen** [comment]
I think this might be a potential solution to the low precision problem. Training on a constant background means the Poisson noise is homoscedastic (same variance everywhere) when there are no objects. On a real image, the background varies, so the Poisson noise is heteroscedastic when there are no objects. 

Since the encoder is trained to expect the same amount of noise everywhere, it is less robust to changes in background. Specifically, it may detect object that aren't there when the background is higher.
