### ISSUE TITLE
Add code for download coadd_catalog

### ISSUE THREAD

**Issue by dereklhansen** [prob-ml/bliss#470]
We have the coadd catalog for a particular sdss frame in [coadd_catalog_94_1_12.fits](https://github.com/prob-ml/bliss/blob/master/data/coadd_catalog_94_1_12.fits). It would be good to document where this file came from, especially if we want to extend our analysis to different frames.

**Comment by dereklhansen** [comment]
I'm happy to do this myself, but I'm having a hard time figuring out where this catalog came from (I'd also like to know for my upcoming presentation). @jeff-regier @ismael-mendoza

**Comment by jeff-regier** [comment]
Ismael and I discussed using the DeCALS catalog instead of the SDSS coadd catalog as the "ground truth" for our experiments. Those catalogs are here: https://portal.nersc.gov/cfs/cosmo/data/legacysurvey/dr9/south/tractor/

That said, it's not clear which is better. Coadd is based on more data so it may be more accurate for flux measurements, but it gets some simple things wrong (e.g., missing galaxies entirely).

**Comment by ismael-mendoza** [comment]
This reference table is also helpful: https://www.legacysurvey.org/dr9/files/#sweep-brickmin-brickmax-fits

**Comment by jeff-regier** [comment]
Instructions for downloading coadd catalogs:
https://github.com/jeff-regier/Celeste.jl/wiki/About-SDSS-and-Stripe-82#how-to-get-ground-truth-data-for-stripe-82
