### ISSUE TITLE
EncoderCNN lacks nonlinearities

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#677]
`EncoderCNN` is a network with 3 blocks of 3 `ConvBlocks` each, each containing 3 `Conv2d` layers; i.e. 27 `Conv2d` layers in total. But these `Conv2d` layer aren't separated by any nonlinearities, e.g., a relu or a maxpool. I wonder if a shallower network would work just as well if given more nonlinearities.

A related issue: currently we're using `EncoderCNN` for all sorts of estimation tasks. But for some tasks, like counting the number of light sources in a tile, an architecture that uses maxpooling may work better. 

https://github.com/prob-ml/bliss/blob/57ae82713c620127b614bdb6fdedffbdc797dbb5/bliss/models/detection_encoder.py#L595-L601

**Comment by dereklhansen** [comment]
I don't think the problem is quite as bad as it looks. Within the forward method of ConvBlock, there is a call to ReLU between the first and second Conv2D layers (`conv1` and `conv2`). There is no ReLU call between `conv2` and the optional downsampling layer (`sc_conv`). However, this only applies to cases where `downsample==True`.

https://github.com/prob-ml/bliss/blob/57ae82713c620127b614bdb6fdedffbdc797dbb5/bliss/models/detection_encoder.py#L635-L651

**Comment by dereklhansen** [comment]
It did take me a bit to figure this out. I think things would be easier to read if we used a `nn.Sequential` block - something we could work on tomorrow during the hackathon.
