### ISSUE TITLE
probabilistic non-maximal suppression

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#806]

**Comment by aakashdp6548** [comment]
The overall objective of this issue is we want to probabilistically decide which tile a source close to the boundary belongs to. This [link](https://www.overleaf.com/read/pzgfmgymqkkb) explains the details of the approach and some basic implementation ideas. 

This will be divided across separate, mostly independent PRs:
- [ ] Adding a new `RegionCatalog` class + relevant infrastructure for non-constant width regions (#879)
- [ ] Update generation to satisfy constraints on which regions sources can be in
- [ ] Encoder changes - loss computation, `variational_mode`
